### ISSUE TITLE
Windows 7

### ISSUE THREAD

**Issue by harryray33** [HovKlan-DH/HovText#10]
Does this work with Win 7?

Thanks

**Comment by HovKlan-DH** [comment]
Yes, it should work on Windows 7 also but it is not supported ;-) You need .NET Framework 4.8 or newer to be installed.

If you view the graph for the operating system (which is brand new, from today only) here, https://hovtext.com/funfacts/ then you can see others are using Windows 7. If this is not working in Windows 7, then I kindly ask for you to enable troubleshoot logging and send this file or information when you experience any problems.

**Comment by HovKlan-DH** [comment]
I assume me previous response is sufficient but otherwise do not hesitate to reach out to me.
